#!/usr/bin/env bash

echo "tmux-pane-tabs - Panes as browser/yazi tabs"
echo ""
echo "Enter pane-tabs mode:    prefix + t"
echo "────────────────────────────────────────────"
echo "  t   Create new pane (horizontal split)"
echo "  v   Create new pane (vertical split)"
echo "  c   Close current pane"
echo "  r   Rename current pane"
echo "  n   Next pane (zoomed)"
echo "  p   Previous pane (zoomed)"
echo "  0-9 Jump to pane by number (zoomed)"
echo "  f   Toggle tab strip display"
echo "  ?   Show this help"
echo ""
echo "All pane jumps auto-zoom (hidden panes stay hidden)."
echo "Use prefix + M-z to toggle zoom manually."
echo ""
echo "See docs/ for full documentation."
